version: '3.1'

services:
  node:
    image: "node:carbon"
    container_name: baker_ui
    user: "node"
    working_dir: /home/node/app/ui
    volumes:
      - ./:/home/node/app/ui
    ports:
      - "3000:3000"
    command: bash -c "npm i && npm start"

